DROP DATABASE ExamManagement;
CREATE DATABASE ExamManagement;
USE ExamManagement;
CREATE TABLE STUDENT(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL
);
CREATE TABLE ADMIN(
    USERNAME VARCHAR(40) PRIMARY KEY NOT NULL,
    FIRSTNAME VARCHAR(40) NOT NULL,
    LASTNAME VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PASSWORD VARCHAR(40) NOT NULL
);
INSERT INTO ADMIN VALUES('admin','admin','admin','admin','admin');


-- insert into STUDENT(FIRSTNAME,LASTNAME,EMAIL,PASSWORD) values('BHARGAB','HAZARIKA','MAXY@HELL.COM','GGYYGUH');