/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;

import exam.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.TimerTask;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.Timer;
import javax.swing.UIManager;

/**
 *
 * @author maxyspark
 */
public class ShowQuestionsFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditQuestionsFrame
     */
    public ShowQuestionsFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        customInit();
        nextQuestions();
    }
    
    public ShowQuestionsFrame(String email) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.email = email;
        customInit();
        nextQuestions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        questionNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        question = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        aOption = new javax.swing.JTextField();
        bOption = new javax.swing.JTextField();
        cOption = new javax.swing.JTextField();
        dOption = new javax.swing.JTextField();
        nextBtn = new javax.swing.JButton();
        prevBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tMin = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        tSec = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        heading.setFont(new java.awt.Font("Courier 10 Pitch", 1, 36)); // NOI18N
        heading.setText("Edit And Add Questions");
        heading.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel1.setText("Question Number");

        questionNumber.setEditable(false);
        questionNumber.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        questionNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        questionNumber.setText("0");

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel2.setText("Question");

        question.setEditable(false);
        question.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        jLabel3.setText("Options");

        jLabel4.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("A");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("B");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel6.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("D");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel7.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("C");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        aOption.setEditable(false);
        aOption.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        aOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aOptionMouseClicked(evt);
            }
        });

        bOption.setEditable(false);
        bOption.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        bOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bOptionMouseClicked(evt);
            }
        });

        cOption.setEditable(false);
        cOption.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        cOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cOptionMouseClicked(evt);
            }
        });

        dOption.setEditable(false);
        dOption.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        dOption.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dOptionMouseClicked(evt);
            }
        });

        nextBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        prevBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        prevBtn.setText("Prev");
        prevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel8.setText("Time");

        tMin.setEditable(false);
        tMin.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        tMin.setText("0");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        jTextField2.setText(":");

        tSec.setEditable(false);
        tSec.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        tSec.setText("0");

        submitBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tMin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tSec, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(137, 137, 137))
                                .addComponent(questionNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(question)
                            .addComponent(bOption)
                            .addComponent(cOption)
                            .addComponent(dOption)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aOption, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(100, 100, 100))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(questionNumber)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(question, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aOption, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bOption, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cOption, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dOption, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        if(ans.size()<currentRow-1) {
            ans.add("NA");
        }
        nextQuestions();
    }//GEN-LAST:event_nextBtnActionPerformed

    private void prevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevBtnActionPerformed
        prevQuestions();
    }//GEN-LAST:event_prevBtnActionPerformed

    private void aOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aOptionMouseClicked
        aOption.setBackground(Color.green);
        bOption.setBackground(defColor);
        cOption.setBackground(defColor);
        dOption.setBackground(defColor);

        if(ans.size()<currentRow-1) {
            ans.add("A");
        } else {
            ans.set(currentRow-2,"A");
        }

    }//GEN-LAST:event_aOptionMouseClicked

    private void bOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOptionMouseClicked
        bOption.setBackground(Color.green);
        aOption.setBackground(defColor);
        cOption.setBackground(defColor);
        dOption.setBackground(defColor);

        if(ans.size()<currentRow-1) {
            ans.add("B");
        } else {
            ans.set(currentRow-2,"B");
        }

    }//GEN-LAST:event_bOptionMouseClicked

    private void cOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cOptionMouseClicked
        cOption.setBackground(Color.green);
        aOption.setBackground(defColor);
        bOption.setBackground(defColor);
        dOption.setBackground(defColor);

        if(ans.size()<currentRow-1) {
            ans.add("C");
        } else {
            ans.set(currentRow-2,"C");
        }
        
    }//GEN-LAST:event_cOptionMouseClicked

    private void dOptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dOptionMouseClicked
        dOption.setBackground(Color.green);
        aOption.setBackground(defColor);
        bOption.setBackground(defColor);
        cOption.setBackground(defColor);
        
        if(ans.size()<currentRow-1) {
            ans.add("D");
        } else {
            ans.set(currentRow-2,"D");
        }
        
    }//GEN-LAST:event_dOptionMouseClicked

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        if(ans.size()<currentRow-1) {
            ans.add("NA");
        }
        submitFlag = 1;
        disableComp();
        evaluate();
    }//GEN-LAST:event_submitBtnActionPerformed

    // load exam list
    
    private void nextQuestions() {
        
        Connection c = null;
        Statement s;
        try {
          Class.forName("com.mysql.jdbc.Driver");
          c=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ExamManagement","root","");
          s=c.createStatement();

         //Query
            
         ResultSet rs = s.executeQuery("SELECT * FROM EXAM_"+examId+" WHERE ID="+currentRow);
         if(rs.next()) {
              questionNumber.setText(Integer.toString(currentRow));
              question.setText(rs.getString("Q"));
              aOption.setText(rs.getString("A"));
              bOption.setText(rs.getString("B"));
              cOption.setText(rs.getString("C"));
              dOption.setText(rs.getString("D"));
              
              if(currentRow==totalQuestion) {
                  nextBtn.setEnabled(false);
                  prevBtn.setEnabled(true);
              }
              currentRow++;
              setAnsColor();
         } 
      } catch(Exception e) {
          JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
      } finally {
          try{c.close();}catch(Exception e){}
      }  
    }
    
    private void prevQuestions() {     
        
        Connection c = null;
        Statement s;
        try {
          Class.forName("com.mysql.jdbc.Driver");
          c=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ExamManagement","root","");
          s=c.createStatement();

         //Query
        currentRow--;
        setAnsColor();
         ResultSet rs = s.executeQuery("SELECT * FROM EXAM_"+examId+" WHERE ID="+currentRow);
         if(rs.next()) {
              questionNumber.setText(Integer.toString(currentRow));
              question.setText(rs.getString("Q"));
              aOption.setText(rs.getString("A"));
              bOption.setText(rs.getString("B"));
              cOption.setText(rs.getString("C"));
              dOption.setText(rs.getString("D"));
              
              if(currentRow==1) {
                  prevBtn.setEnabled(false);
                  nextBtn.setEnabled(true);
              }
              
         } 
      } catch(Exception e) {
          JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
      } finally {
          try{c.close();}catch(Exception e){}
      }  
    }
    
    public void evaluate() {
        Result result = new Result(ans,examId,email,totalQuestion);
        result.getAns();
    }
    
    public void disableComp(){
        aOption.setEnabled(false);
        bOption.setEnabled(false);
        cOption.setEnabled(false);
        dOption.setEnabled(false);
        prevBtn.setEnabled(false);
        nextBtn.setEnabled(false);
        submitBtn.setEnabled(false);
    
    }
    
    public void setAnsColor(){
            aOption.setBackground(defColor);
            bOption.setBackground(defColor);
            cOption.setBackground(defColor);
            dOption.setBackground(defColor); 

    }
    // custom init
    
    final public void customInit(){
        Connection c = null;
        Statement s;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ExamManagement","root","");
            s=c.createStatement();
            
            ResultSet ce = s.executeQuery("SELECT * FROM CURRENTEXAM");
            while(ce.next()) {
                examId =  ce.getInt("ID");
                examTime = ce.getInt("TIME");
                examTime -= 1;
            }
            ResultSet r = s.executeQuery("SELECT * FROM EXAMS WHERE ID="+examId);
            r.next();
            totalQuestion = r.getInt("TOTALQUESTION");
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
        } finally {
            try{c.close();}catch(Exception e){}
        } 
         
        
        
        // Timer
        
        Timer timer = new Timer();
        TimerTask myTask = new TimerTask() {
        @Override
            public void run() {
                tMin.setText(Integer.toString(examTime));
                tSec.setText(Integer.toString(sec));
                if(sec==0) {
                    examTime -= 1;
                    sec=59;
                } else{
                    sec -= 1;
                }
                if(submitFlag==1 || (examTime==0 && sec==0)) {
                   
                    timer.cancel();
                    timer.purge();
                    tMin.setText("00");
                    tSec.setText("00");
                    disableComp();
                    if(submitFlag==0) {
                        JOptionPane.showMessageDialog(null, "Times Up","Message",JOptionPane.INFORMATION_MESSAGE);
                        evaluate();
                    }
                    
                    return;  
                }
            }
        };

        timer.schedule(myTask, new Date(), 1000);
        
        
         
        heading.setHorizontalAlignment(JLabel.CENTER);
        jLabel8.setHorizontalAlignment(JLabel.CENTER);
        tMin.setHorizontalAlignment(JLabel.CENTER);
        tSec.setHorizontalAlignment(JLabel.CENTER);
        // Pading Text Fields
        question.setBorder(BorderFactory.createCompoundBorder(question.getBorder(), BorderFactory.createEmptyBorder(8, 5, 8, 5)));
        aOption.setBorder(BorderFactory.createCompoundBorder(aOption.getBorder(), BorderFactory.createEmptyBorder(8, 5, 8, 5)));
        bOption.setBorder(BorderFactory.createCompoundBorder(bOption.getBorder(), BorderFactory.createEmptyBorder(8, 5, 8, 5)));
        cOption.setBorder(BorderFactory.createCompoundBorder(cOption.getBorder(), BorderFactory.createEmptyBorder(8, 5, 8, 5)));
        dOption.setBorder(BorderFactory.createCompoundBorder(dOption.getBorder(), BorderFactory.createEmptyBorder(8, 5, 8, 5)));

    }
    Color defColor = UIManager.getColor ( "JTextField.background" );
    int totalQuestion;
    int currentRow=1;
    int examId = 0;    
    int examTime = 0;
    int sec = 59;
    String email;
    int submitFlag = 0;
    ArrayList<String> ans = new ArrayList<String>();
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aOption;
    private javax.swing.JTextField bOption;
    private javax.swing.JTextField cOption;
    private javax.swing.JTextField dOption;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton prevBtn;
    private javax.swing.JTextField question;
    private javax.swing.JTextField questionNumber;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField tMin;
    private javax.swing.JTextField tSec;
    // End of variables declaration//GEN-END:variables
}
