/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author debasmit
 */
public class ExamManagementFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form ExamManagementFrame
     */
    public ExamManagementFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        customInit();
        loadExamList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        newExam = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        selectExam = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        examTable = new javax.swing.JTable();
        heading = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        setTimer = new javax.swing.JSpinner();
        editExam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        cExam = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        newExam.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        newExam.setText("Start a new Exam");
        newExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newExamActionPerformed(evt);
            }
        });

        updateBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        selectExam.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        selectExam.setMaximumRowCount(0);
        selectExam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));

        jLabel2.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        jLabel2.setText("Select Exam By Id");

        jLabel3.setFont(new java.awt.Font("Courier 10 Pitch", 1, 20)); // NOI18N
        jLabel3.setText("Set Duration");

        examTable.setFont(new java.awt.Font("Courier 10 Pitch", 1, 15)); // NOI18N
        examTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sl No", "Id", "Exam Name", "Total Q's"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        examTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        examTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(examTable);
        if (examTable.getColumnModel().getColumnCount() > 0) {
            examTable.getColumnModel().getColumn(0).setMinWidth(45);
            examTable.getColumnModel().getColumn(0).setPreferredWidth(45);
            examTable.getColumnModel().getColumn(0).setMaxWidth(45);
            examTable.getColumnModel().getColumn(1).setMinWidth(35);
            examTable.getColumnModel().getColumn(1).setMaxWidth(35);
            examTable.getColumnModel().getColumn(2).setResizable(false);
            examTable.getColumnModel().getColumn(3).setMinWidth(80);
            examTable.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        heading.setFont(new java.awt.Font("Courier 10 Pitch", 1, 36)); // NOI18N
        heading.setText("Exam Dasahboard");
        heading.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));

        jLabel5.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel5.setText("Exam Lists");

        setTimer.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        setTimer.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        editExam.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        editExam.setText("Edit Exam Details and Questions");
        editExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editExamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier 10 Pitch", 1, 24)); // NOI18N
        jLabel1.setText("Set Current Exam");

        cancelBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        cancelBtn.setText("Go To Admin Dashboard");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        cExam.setFont(new java.awt.Font("Courier 10 Pitch", 1, 19)); // NOI18N
        cExam.setForeground(new java.awt.Color(237, 23, 68));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(heading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editExam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(newExam, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(setTimer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(selectExam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cExam, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newExam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cExam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(selectExam, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setTimer, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editExam, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newExamActionPerformed
        this.dispose();
        NewExamFrame nef = new NewExamFrame();
        nef.setVisible(true);
    }//GEN-LAST:event_newExamActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        AdminDashboardFrame adf = new AdminDashboardFrame();
        this.dispose();
        adf.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void examTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examTableMouseClicked
        int row = examTable.getSelectedRow();
        selecetedId = Integer.parseInt(examTable.getValueAt(row, 1).toString());
        editExam.setEnabled(true);
    }//GEN-LAST:event_examTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        JComboBox examBox = selectExam;
        int sel_id = (int) examBox.getSelectedItem();
        int time;
        try {
            setTimer.commitEdit();
        } catch ( java.text.ParseException e ) {  }
        time = (Integer) setTimer.getValue();

        Connection c = null;
        Statement s;    
        try {

            Class.forName("com.mysql.jdbc.Driver");
            c=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ExamManagement","root","");
            s=c.createStatement();

         //Query
            s.executeUpdate("DELETE FROM CURRENTEXAM");
            s.executeUpdate("INSERT INTO CURRENTEXAM VALUES("+sel_id+","+time+")");
            ResultSet ce = s.executeQuery("SELECT * FROM CURRENTEXAM");
            while(ce.next()) {
                cExam.setText("Current Exam Id : "+ce.getInt("ID")+" and Time : "+ce.getInt("TIME")+" Mins");
            }
            JOptionPane.showMessageDialog(this, "Current Exam Set to \nExam Id = "+sel_id+"\nDuration = "+time+" Mins","Message",JOptionPane.INFORMATION_MESSAGE);

      } catch(Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
      } finally {
            try{c.close();}catch(Exception e){}
      }  
    }//GEN-LAST:event_updateBtnActionPerformed

    private void editExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editExamActionPerformed
        this.dispose();
        ExamQuesionAddFrame eqaf = new ExamQuesionAddFrame(selecetedId);
        eqaf.setVisible(true);
    }//GEN-LAST:event_editExamActionPerformed

    // load exam list
    
    private void loadExamList() {
        // load exam title from database and display in table
        JComboBox examBox = selectExam;
        examBox.removeAllItems();
        Connection c = null;
        Statement s;
                  try {
                    
                    
                    
                    Class.forName("com.mysql.jdbc.Driver");
                    c=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/ExamManagement","root","");
                    s=c.createStatement();
                    int row = 0;
                    int x=0;

                   //Query
                   ResultSet ce = s.executeQuery("SELECT * FROM CURRENTEXAM");
                   while(ce.next()) {
                       cExam.setText("Current Exam Id : "+ce.getInt("ID")+" and Time : "+ce.getInt("TIME")+" Mins");
                   }
                   ResultSet rs = s.executeQuery("SELECT * FROM EXAMS"); 

                   while(rs.next()) {
                        ((DefaultTableModel)examTable.getModel()).addRow(new Object[]{});
                        ((DefaultTableModel)examTable.getModel()).setValueAt(++x, row, 0);
                        ((DefaultTableModel)examTable.getModel()).setValueAt(rs.getInt("ID"), row, 1);
                        ((DefaultTableModel)examTable.getModel()).setValueAt(rs.getString("TITLE"), row, 2);
                        ((DefaultTableModel)examTable.getModel()).setValueAt(rs.getInt("TOTALQUESTION"), row, 3);
                        examBox.addItem(rs.getInt("ID"));
                        
                        row++;
                   }

                } catch(Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(),"Exception",JOptionPane.ERROR_MESSAGE);
                } finally {                    
                    try{c.close();}catch(Exception e){}
                }  
    }
    
    // custom init
    
    final public void customInit(){
        heading.setHorizontalAlignment(JLabel.CENTER);
        editExam.setEnabled(false);
    }

    int selecetedId=0;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cExam;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton editExam;
    private javax.swing.JTable examTable;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newExam;
    private javax.swing.JComboBox selectExam;
    private javax.swing.JSpinner setTimer;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
